apps/perp/src/app/markets/components/market-table-column.tsx
https://discord.com/channels/924442927399313448/1272875793978097714
=> fix(perps): update sorting on markets page

apps/bgt-station/src/app/gauge/[gaugeAddress]/banner.tsx, apps/bgt-station/src/app/gauge/[gaugeAddress]/gauge-details.tsx, apps/dex/src/app/pool/PoolPageContent.tsx, apps/hub/src/app/pool/PoolPageContent.tsx, apps/hub/src/app/vaults/[gaugeAddress]/components/banner.tsx, apps/hub/src/app/vaults/[gaugeAddress]/components/gauge-details.tsx, apps/perp/src/app/vault/page.tsx, packages/shared-ui/src/bgt-station-banner.tsx
=> FIX link to bgt station gauge

apps/honey/instrumentation.ts, apps/honey/next.config.mjs, apps/honey/package.json, apps/honey/sentry.client.config.ts, apps/honey/sentry.edge.config.ts, apps/honey/sentry.server.config.ts, apps/hub/instrumentation.ts, apps/hub/next.config.mjs, apps/hub/package.json, apps/hub/sentry.client.config.ts, apps/hub/sentry.edge.config.ts, apps/hub/sentry.server.config.ts, apps/lend/instrumentation.ts, apps/lend/next.config.mjs, apps/lend/package.json, apps/lend/sentry.client.config.ts, apps/lend/sentry.edge.config.ts, apps/lend/sentry.server.config.ts, apps/perp/instrumentation.ts, apps/perp/next.config.mjs, apps/perp/package.json, apps/perp/sentry.client.config.ts, apps/perp/sentry.edge.config.ts, apps/perp/sentry.server.config.ts, pnpm-lock.yaml
This PR updates Sentry and sets sentry variables through process.env so we can manage them through sentry's vercel integration.
=> chore: Add sentry

apps/perp/src/app/berpetuals/[market]/page.tsx, apps/perp/src/app/berpetuals/components/order-history-table.tsx, apps/perp/src/app/berpetuals/components/order-history.tsx, apps/perp/src/endpoints/index.ts
=> fix(perp): data table keeps loading if no wallet is connected

apps/bgt-station/src/app/layout.tsx, apps/dex/src/app/layout.tsx, apps/honey/src/app/layout.tsx, apps/lend/src/app/layout.tsx, apps/perp/src/app/layout.tsx, packages/shared-ui/src/binance-version-handler.tsx, packages/shared-ui/src/index.ts, packages/wagmi/src/context/context.tsx
User should only see the different if they are using binance web3 wallet, or there should not be any difference.
=> feat: add binance prompt for version check

apps/bgt-station/package.json, apps/dex/package.json, apps/honey/package.json, apps/hub/package.json, apps/lend/package.json, apps/perp/package.json, package.json, packages/shared-ui/package.json, pnpm-lock.yaml
This should use the proper thumbnail links, also fixed on v2 with #72 . We should check after merging.
=> Fix missing thumbnails on bartio

apps/perp/src/app/berpetuals/components/asset-cards/getAssetCards.tsx, apps/perp/src/app/berpetuals/components/asset-cards/positions.tsx, apps/perp/src/app/berpetuals/components/order-chart.tsx, apps/perp/src/app/berpetuals/components/order-history-header.tsx, apps/perp/src/app/berpetuals/components/order-history.tsx, apps/perp/src/app/components/close-position-modal.tsx, apps/perp/src/app/components/table-columns/positions.tsx, apps/perp/src/app/components/total-amount.tsx, apps/perp/src/app/components/update-position-modal.tsx, apps/perp/src/app/portfolio/components/stats.tsx, apps/perp/src/app/portfolio/components/user-assets.tsx, apps/perp/src/hooks/usePollOpenPositions.ts, apps/perp/src/types/market.ts, apps/perp/src/types/order-history.ts
hey @BrownBrownBear , this should fix the bug from discord. was there a reason for returning undefined if there were more than 10 positions? it was probably just forgotten there.
if this works i'll cherry pick the commit on bartio
=> fix(perp): calculate total unrealized pnl correctly

.scripts/ignore-if-not-nextjs.sh, apps/honey/src/app/api/useHoneyEvents.ts, apps/honey/src/hooks/useHoneyEvents.ts, apps/honey/src/utils/graph-utils.ts
Adds a bash script which checks if there is a next.config.mjs file in the folder provided as argument.
=> ci: ignore deprecated projects

graphql.config.ts, packages/graphql/codegen.ts, packages/graphql/package.json, packages/graphql/src/modules/governance/codegen.ts, packages/graphql/src/modules/governance/index.ts, pnpm-lock.yaml
adds types generated by graph-codegen
=> feat: grapql codegen

apps/hub/src/app/governance/[genre]/components/delegate-modal.tsx, apps/hub/src/app/governance/[genre]/components/proposal-card.tsx, apps/hub/src/app/governance/[genre]/components/proposals-list.tsx, apps/hub/src/app/governance/components/status-badge.tsx, apps/hub/src/app/governance/governance-genre-helper.tsx, apps/hub/src/app/governance/helper.ts, apps/hub/src/app/governance/proposal/[proposalId]/components/cancel-button.tsx, apps/hub/src/app/governance/proposal/[proposalId]/components/proposal-details.tsx, apps/hub/src/app/governance/proposal/[proposalId]/components/proposal-timeline.tsx, apps/hub/src/app/governance/proposal/[proposalId]/page.tsx, apps/hub/src/app/validators/validator/delegate-modal.tsx, apps/hub/src/hooks/useCreateProposal.ts, packages/berajs/src/actions/governance/getProposalDetails.ts, packages/berajs/src/types/governance.ts, packages/graphql/src/modules/governance/query.ts
progress on proposal detail, cards, handled different states. 
fixes proposal route 404 on vercel.
=> governance ui updates 

.env.v2, .github/workflows/ipfs-deploy.yml, .github/workflows/ipfs-static-build-test.yml, .vscode/settings.json, apps/hub/src/app/Providers.tsx, apps/hub/src/app/validators/components/boost-queue.tsx, apps/hub/src/app/validators/components/confirmation-card.tsx, apps/hub/src/hooks/useValidatorEstimatedBgtPerYear.ts, graphql.config.ts, packages/berajs/src/actions/bgt/getBgtApy.ts, packages/berajs/src/contexts/block-time-provider.tsx, packages/berajs/src/contexts/index.ts, packages/berajs/src/hooks/modules/bgt/useBgtApy.ts, packages/berajs/src/hooks/modules/governance/useCancellerRole.ts, packages/berajs/src/types/global.ts, packages/config/env/index.ts, packages/graphql/codegen.ts, packages/graphql/package.json, packages/graphql/src/modules/chain/codegen.ts, packages/graphql/src/modules/chain/index.ts, packages/graphql/src/modules/chain/query.ts, packages/graphql/src/modules/clients/blocks-client.ts, packages/graphql/src/modules/clients/index.ts, packages/graphql/src/modules/governance/codegen.ts, packages/graphql/src/modules/governance/query.ts, packages/graphql/src/modules/index.ts, packages/graphql/src/modules/types.ts, pnpm-lock.yaml
Changelog:
- fix codegen errors when generating from multiple schemas
- adds blocks sugraph
- adds `useBlockTime` hook to be used within its provider
- removes all instances of NEXT_PUBLIC_BLOCKTIME in favor of useBlockTime
I'm not familiar with all instances where blocktime was used, but i hope they all work properly. please check
=> Average block time on chain

packages/berajs/jest.config.js, packages/berajs/package.json, packages/berajs/src/utils/truncateHash.test.ts, packages/berajs/tsconfig.json, pnpm-lock.yaml
Setup Jest with default configuration and add test `truncateHash.test.ts` as sample
=> feat: init setup jest + add sample test

apps/hub/src/app/pools/create/CreatePageContent.tsx, apps/hub/src/components/create-pool/create-pool-initial-liquidity-input.tsx, apps/hub/src/components/create-pool/create-pool-input.tsx, apps/hub/src/hooks/useCreatePool.ts, packages/ui/src/input.tsx
Reverts berachain/monobera#175
=> Revert "Feature/balancer/pool create ux imp"

.github/workflows/quality.yml, apps/hub/src/app/pools/PoolsTable.tsx, apps/hub/src/app/pools/[poolId]/details/PoolChart.tsx, apps/hub/src/app/pools/[poolId]/details/PoolPageContent.tsx, biome.json, packages/berajs/src/actions/dex/getPoolHistoricalData.ts, packages/berajs/src/actions/dex/index.ts, packages/berajs/src/hooks/modules/dex/index.ts, packages/berajs/src/hooks/modules/dex/usePoolHistoricalData.ts, packages/graphql/src/modules/dex/api.graphql, packages/shared-ui/src/table/v2/lib/components/core/table-row.tsx, packages/shared-ui/src/table/v2/lib/simple-table/simple-table.tsx
=> Bfe 275 bex restore charts on pool page

apps/hub/src/app/pools/create/CreatePageContent.tsx
This changes the ownership address and type to Governance, per #210 the FE to change ownership is still hidden, so this is effectively the only ownership option via FE.
=> Default ownership is now Governance

packages/berajs/src/abi/honey/honeyFactory.ts
update Honey Factory Abi after the changes to the method 'isPegged' visibility. internal -> external
=> chore: update Honey Factory abi

apps/honey/src/hooks/usePsm.tsx, packages/berajs/src/abi/honey/honeyFactory.ts
Update the HoneyFactory abi and the changed methods:
Mint and Redeem with the new prop expectBasketMode
=> refactor(honey): update honey factor abi & mint/redeem methods call

apps/hub/src/app/Providers.tsx, apps/hub/src/app/layout.tsx, apps/hub/src/components/hero-card.tsx, packages/shared-ui/src/connect-button.tsx, packages/shared-ui/src/connected-wallet-popover.tsx, packages/shared-ui/src/header.tsx, packages/shared-ui/src/settings.tsx
=> Bfe 266 hub disable light mode

apps/honey/src/components/swap-card.tsx
change the style on the inputs of the honey swapper to enphasize with one is the input and which the output ONLY IN BASKET MODE
=> style(honey): input & output clarify

apps/hub/src/app/rewards/my-incentives-table.tsx, apps/hub/src/app/validators/components/confirmation-card.tsx, apps/hub/src/app/validators/components/delegated-address-table.tsx, apps/hub/src/app/validators/validator/components/ValidatorDetails.tsx, apps/hub/src/app/validators/validator/components/ValidatorPolData.tsx, apps/hub/src/app/vaults/[gaugeAddress]/components/VaultDetails.tsx, apps/hub/src/columns/gauge-incentives-columns.tsx, apps/hub/src/columns/general-validator-columns.tsx, apps/hub/src/components/bribes-tooltip.tsx, apps/hub/src/components/global-gauge-weight-table.tsx, apps/hub/src/utils/formatted-chart-data.ts, packages/berajs/src/actions/bgt/getBGTGlobalInfo.ts, packages/berajs/src/actions/bgt/getRewardVaultIncentives.ts, packages/berajs/src/hooks/modules/bgt/useValidator.ts, packages/berajs/src/types/staking.ts, packages/graphql/src/modules/pol/api.graphql, packages/graphql/src/modules/pol/subgraph.graphql
Backend schema was refactored along with subgraph to match with updated berachain terminology. This PRs removes deprecated names in favor of updated ones.
=> refactor(pol): updates API naming

apps/honey/next.config.mjs, apps/hub/next.config.mjs, apps/lend/next.config.mjs, apps/lend/src/app/dashboard/user-deposits.tsx, apps/perp/next.config.mjs, packages/berajs/src/utils/tokenWrapping.ts, packages/wagmi/src/constants/beraToken.ts, packages/wagmi/src/constants/wberaToken.ts
This needs to go in first: https://github.com/berachain/internal-dapps-env/pull/12
=> chore(repo): remove aws token logo links from repo Refs BFE-453

apps/hub/src/app/pools/create/CreatePageContent.tsx
fix the grid layout in the create a pool page to align with the design (there was an extra flex wrapper that shouldn't have been there)
=> BFE-467: Fix issue with grid layout in the Create a Pool page
